spring.application.name=carematch-server
# default set
spring.profiles.active=local

# Shared Server Setup
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true


# Performance & API (important)
# Java 21 virtual thread activation (essential for high performance)
spring.threads.virtual.enabled=true


# API default set = false. after the transaction, it automatically return the connection.
spring.jpa.open-in-view=false


# during JSON response,  date value serialized to a string '2026-01-22T...'
# spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Seoul


# File Upload Limit
# default set = -1(no limit) or could be smaller. set explicitly. can change later.
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB